sudo: required

language: c

env:
   global:
      - OS_TESTED_CL="clearlinux"
      - OS_TESTED_UBUNTU="ubuntu16.04"
      - OS_TESTED_FEDORA="fedora28"

   matrix:
      - RELEASE=0
        PLATFORM=sbl

      - RELEASE=1
        PLATFORM=sbl

      - RELEASE=0
        PLATFORM=uefi

      - RELEASE=1
        PLATFORM=uefi

services:
   - docker

before_install:
   - docker build -t ${OS_TESTED_CL} -f .travis-dockerfiles/Dockerfile.${OS_TESTED_CL} .
   - docker images

install: true

script:
   - docker run -v $PWD:/root/acrn ${OS_TESTED_CL} /bin/bash -c "make clean && make PLATFORM=$PLATFORM RELEASE=$RELEASE"
